version: "3.8"
services:
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '8000:5000'
    volumes: 
      - ./backend:/app
      - /app/node_modules

volumes: 
  data:
  logs:
